"""empty message

Revision ID: 644fe82d0c2f
Revises: 
Create Date: 2025-06-18 21:31:12.372165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644fe82d0c2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('salt', sa.LargeBinary(length=255), nullable=True, comment='加密盐'),
    sa.Column('email', sa.String(length=50), nullable=False, comment='邮箱'),
    sa.Column('status', sa.Integer(), nullable=False, comment='用户账号状态(0停用 1正常)'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='超级权限(0否 1是)'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号'),
    sa.Column('join_time', sa.DateTime(), nullable=False, comment='注册时间'),
    sa.Column('last_login_time', sa.DateTime(), nullable=True, comment='上次登录'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    # ### end Alembic commands ###
