"""add a new filed named 'gender' for user

Revision ID: a605bcc089a0
Revises: 644fe82d0c2f
Create Date: 2025-06-18 21:32:03.797957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a605bcc089a0'
down_revision = '644fe82d0c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('gender', sa.String(length=8), nullable=True, comment='性别'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'gender')
    # ### end Alembic commands ###
